image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package

test/build:
  image: maven:3.6.0-jdk-11
  stage: build
  script: "mvn clean verify"
  artifacts:
    paths:
    - spring-kotlin/target/*.jar