image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package

test/build:
  image: gradle:jdk11
  stage: build
  script: "./gradlew clean build"
  artifacts:
    paths:
    - spring-kotlin/build/libs/*.jar