image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package

test/build:
  image: gradle:jdk17
  stage: build
  script: "gradle clean build"
  artifacts:
    paths:
      - service/build/libs/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/christian_schmidt/shopping-cart-service:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/christian_schmidt/shopping-cart-service:latest