version: '3'
services:
  academy-api:
    image: registry.gitlab.com/tarent/academy-api:latest
    dns:
    - 8.8.8.8
    ports:
    - 8083:8080
  product-service:
    image: registry.gitlab.com/tarent/product-service-java:latest
    ports:
    - 8081:8080
  shoppingcart-service:
    build:
      context: ./spring-kotlin
      dockerfile: Dockerfile
    ports:
    - 8082:8080