server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    generate-ddl: true

logging:
  config: classpath:logback.xml